sudo: true
services:
  - docker
language: python
cache:
  pip: true
  directories:
    - .mypy_cache
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
os:
  - linux
install:
  - pip install tox-travis
jobs:
  include:
    - stage: release-test
      script: RELEASE_SKIP=head ./release-test.sh
script: tox
branches:
  only:
    - master
notifications:
  email: false
